environments:
  prod:
    values:
    - ./prod/values/kafka.yaml
  dev:
    values:
    - ./dev/values/kafka.yaml
---
releases:
  - name: kafka-prod
    labels:
      app: kafka
    wait: true
    chart: oci://registry-1.docker.io/bitnamicharts/kafka
    namespace: prod
    version: 31.5.0
    values:
      - ./prod/values/kafka.yaml
  - name: kafka-dev
    labels:
      app: kafka
    wait: true
    chart: oci://registry-1.docker.io/bitnamicharts/kafka
    namespace: dev
    version: 31.5.0
    values:
      - ./dev/values/kafka.yaml