apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw12
  namespace: homework
  labels:
    app: hw12
spec:
  selector:
    matchLabels:
      app: hw12
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 33%
      maxUnavailable: 33%
  template:
    metadata:
      labels:
        app: hw12
    spec:
      containers:
        - name: nginx
          image: nginx
          imagePullPolicy: IfNotPresent
          env:
            - name: CUSTOM_PORT
              value: "8000"
            - name: CUSTOM_ROOT
              value: "/homework"
          command: ["/bin/sh", "-c"]
          args: [
            "echo 'server { listen $(CUSTOM_PORT); location / { root $(CUSTOM_ROOT); try_files $uri $uri/ index index.html; } }' \
            >> /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
          ]
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", 'rm /homework/index.html']
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /index.html
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: workdir
              mountPath: /homework
      # These containers are run during pod initialization
      initContainers:
        - name: install
          image: busybox:1.28
          command:
            - wget
            - "-O"
            - "/init/index.html"
            - http://info.cern.ch
          volumeMounts:
            - name: workdir
              mountPath: /init
      dnsPolicy: Default
      volumes:
        - name: workdir
          persistentVolumeClaim:
            claimName: hw12-pvc
            readOnly: false
