apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: demo7-clusterrole
  # labels:
  #   rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
- nonResourceURLs: ["*"]
  verbs: ["*"]