apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mysqls.otus.homework
  namespace: homework
spec:
  group: otus.homework
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                image:
                  type: string
                  x-kubernetes-validations:
                  - rule: "self.startsWith('mysql')"
                database:
                  type: string
                  pattern: '^[a-zA-Z0-9]+$'
                  # x-kubernetes-validations:
                  # - rule: "self.database in ['db01']"
                  #   message: "Database should be db01"
                password:
                  type: string
                  pattern: '^[a-zA-Z0-9$]+$'
                  default: 'Pa$$w0rd'
                  # x-kubernetes-validations:
                  # - rule: "self.password in ['Pa$$w0rd']"
                  #   message: "Password should be Pa$$w0rd"
                storage_size:
                  type: string
                  x-kubernetes-validations:
                  - rule: "self.endsWith('Gi')"
                  # - rule: "self.storage_size in ['1Gi', '3Gi', '5Gi']"
                  #   message: "Storage_size should be of 1Gi, 3Gi, or 5Gi"
  scope: Namespaced
  names:
    kind: MySQL
    singular: mysql
    plural: mysqls
    shortNames:
      - ct