apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubernetes-networks
  namespace: argocd
  labels:
    name: kubernetes-networks
spec:
  project: otus
  source:
    repoURL: https://github.com/Kuber-2024-10OTUS/klimenko-sergey_repo
    targetRevision: kubernetes-gitops
    path: kubernetes-networks
  destination:
    server: https://kubernetes.default.svc
    namespace: homework
  syncPolicy:
    # automated:
      # enabled: false
    syncOptions:
      - CreateNamespace=true