server:
  enabled: true
  replicaCount: 1
  ingress:
    enabled: true
  ha:
    enabled: true
    replicas: 3
    config: |
      ui = true

      listener "tcp" {
        tls_disable = 1
        address = "[::]:8200"
        cluster_address = "[::]:8201"
      }
      storage "consul" {
        path = "vault"
        address = "consul-consul-server.consul.svc.cluster.local:8500"
      }

      service_registration "kubernetes" {}
injector:
  enabled: true