apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: demo5-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: monitoring
  namespace: homework
  # apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: demo5-clusterrole
  apiGroup: rbac.authorization.k8s.io
