apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: demo5-clusterrole
  # labels:
  #   rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
- apiGroups: ["metrics.k8s.io"]
  resources: ["nodes"]
  verbs: ["get", "watch", "list"]
