apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-example
  namespace: vault
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: otus-cred
  data:
  - secretKey: username
    remoteRef:
      key: cred
      property: username
  - secretKey: password
    remoteRef:
      key: cred
      property: password
  # dataFrom:
  # - extract:
  #     key: cred
  # #     property: foo.nested