apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
  name: vault-auth
  namespace: vault
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: vault-auth
  name: vault-auth-secret
  namespace: vault
type: kubernetes.io/service-account-token