apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: vault
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "otus"
      version: "v2"
      auth:
        # Kubernetes auth: https://www.vaultproject.io/docs/auth/kubernetes
        kubernetes:
          mountPath: "kubernetes"
          role: "otus"
          # Optional service account reference
          serviceAccountRef:
            name: "vault-auth"
          # Optional secret field containing a Kubernetes ServiceAccount JWT
          # used for authenticating with Vault
          # secretRef:
          #   name: "my-secret"
          #   key: "vault"

        # # points to a secret that contains a vault token
        # # https://www.vaultproject.io/docs/auth/token
        # tokenSecretRef:
        #   name: "vault-auth-secret"
        #   key: "token"
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: vault-auth-secret
#   namespace: vault
# data:
#   token: ... # "root"