apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "hw6.fullname" . }}-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  # storageClassName: {{ include "hw6.fullname" . }}-sc
