apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo4-pvc
  namespace: homework
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: my-sc
