apiVersion: v1
kind: Pod
metadata:
  name: init-demo
  namespace: homework
spec:
  containers:
  - name: nginx
    image: nginx
    lifecycle:
      preStop:
        exec:
          command: ["/bin/sh","-c",'rm /homework/index.html']
    ports:
    - containerPort: 8000
    volumeMounts:
    - name: workdir
      mountPath: /homework
  # These containers are run during pod initialization
  initContainers:
  - name: install
    image: busybox:1.28
    command:
    - wget
    - "-O"
    - "/init/index.html"
    - http://info.cern.ch
    volumeMounts:
    - name: workdir
      mountPath: /init
  dnsPolicy: Default
  volumes:
  - name: workdir
    emptyDir: {}
